### PR TITLE
Upgrade to porcupine to v1.8

### PR DESCRIPTION
**Pull request by Tooa**
This pull requests updates `porcupine` to `v1.8`. 

Changes:
* The `porcupine` maintainer changed filenames for keyword files ([reference](https://github.com/Picovoice/porcupine/tree/v1.8/resources/keyword_files/raspberry-pi))
* The `porcupine.py` python binding hasn't changed ([reference](https://raw.githubusercontent.com/Picovoice/porcupine/v1.8/binding/python/porcupine.py))

## Details
* refs https://github.com/rhasspy/rhasspy/issues/65
* See https://picovoice.ai/blog/porcupine-wake-word-engine-v1-8-feature-tour/ for changes

### CODE REVIEW

**Comment by Tooa** [comment]
@synesthesiam I think we need to remove `Python 3.7` [here](https://github.com/rhasspy/rhasspy-wake-porcupine-hermes/blob/master/.github/workflows/tests.yml#L13) when looking at the checks.

**Comment by koenvervloesem** [comment]
Python 3.6 isn't supported anymore. I have removed the build in https://github.com/rhasspy/rhasspy-wake-porcupine-hermes/commit/85ab5917ba5c12a5c931b3ec6ff9d5d0ea242533.

**Comment by NullEnt1ty** [comment]
@Tooa Thanks for working on this! It seems that you ran into a nasty trap:

> The porcupine maintainer changed filenames for keyword files

Well, the keyword files were renamed before they were checked into this repository. If you look at the previous tags in the Porcupine repository, you will note that the filenames were never changed there.

This leads to an exception when Rhasspy tries to load Porcupine, because it uses "porcupine.ppn" as the default keyword file, which lacks a suffix.

```
[DEBUG:2020-06-14 08:44:18,950] rhasspywake_porcupine_hermes: Loading porcupine (kw=['porcupine.ppn'], kwdirs=['/home/dominique/.config/rhasspy/profiles/de/porcupine', '/home/dominique/projects/rhasspy/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/porcupine/resources/keyword_files/linux'], sensitivity=[0.5], library=/home/dominique/projects/rhasspy/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/porcupine/lib/linux/x86_64/libpv_porcupine.so, model=/home/dominique/projects/rhasspy/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/porcupine/lib/common/porcupine_params.pv)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dominique/projects/rhasspy/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py", line 274, in <module>
    main()
  File "/home/dominique/projects/rhasspy/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/__main__.py", line 138, in main
    porcupine_handle = Porcupine(
  File "/home/dominique/projects/rhasspy/rhasspy/rhasspy-wake-porcupine-hermes/rhasspywake_porcupine_hermes/porcupine.py", line 93, in __init__
    raise IOError("could not find keyword file at '%s'" % x)
OSError: could not find keyword file at 'porcupine.ppn'
2020-06-14 08:44:18,959 INFO exited: wake_word (exit status 1; not expected)
```

We have two options here:

1. Keep the suffix (e.g. "porcupine_raspberry-pi.ppn") and adjust the default value (which can be tricky, because it depends on the platform).
2. Remove the suffix from keyword files.

/cc @synesthesiam

**Comment by NullEnt1ty** [comment]
I opened a pull request to quickly fix this issue (by removing the platform suffix).

@synesthesiam Can you take a look at #4?

**Pull request merged**
