### PR TITLE
Porcupine v1.9

### PR DESCRIPTION
**Pull request by Enc3ph4l0n**
Hi @synesthesiam,

Upgraded to Porcupine v1.9. There's a change to the keyword_path/keyword_paths argument which I've amended too.

However, I'm really struggling to test the changes. It runs, but I'm encountering all kinds of problems because I can't seem to hack together enough of a working Rhasspy environment to confirm all is OK.

I installed 'rhasspy-microphone-cli-hermes' but either I've messed up the arguments or there's an issue with the upgrade because the hotword fires relentlessly with every audio block. I thought I could install the .deb package and go down that route, but as you know, it's broken.

Running out of easy paths to confirm all is OK. I thought having 'Microphone-CLI-Hermes' and this package is all that's needed. Am I missing a link between the two that would cause this behaviour?

### CODE REVIEW

**Comment by Enc3ph4l0n** [comment]
Pushed the change into a docker container and found the same behaviour. There's definitely something wrong with the upgrade. Python is just about the only language I've never used in the day job so I'll have to find some time and take a closer look and work out what's going on. Input welcome; I'm sure it's something silly.

**Comment by synesthesiam** [comment]
Thanks! Let me take a look :)

**Comment by synesthesiam** [comment]
OK, I've merged the changes and made some modifications. I went ahead and just switched to the `pvporcupine` library instead of manually keeping all of the files in this repo.

The problem for me was that the index returned by the `process` function needed to be tested with `>= 0`

**Comment by Enc3ph4l0n** [comment]
> OK, I've merged the changes and made some modifications. I went ahead and just switched to the `pvporcupine` library instead of manually keeping all of the files in this repo.

Makes much more sense. Sorry, my PR wasn't very valuable relative to these changes. I've not used Python and whilst I get the gist of what everything is doing, I'd need to brush up to avoid doing more harm than good. I hope to contribute more value to this project in future.

> The problem for me was that the index returned by the `process` function needed to be tested with `>= 0`

Yep, saw your commit before your comment. That would explain the behaviour I was seeing. Knew it was something small!

**Comment by synesthesiam** [comment]
No worries, thank you for the PR :)

**Pull request merged**
